// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAG9zvukee4PtoW7k2YWIn6MufpU695BDA',
    appId: '1:335135674224:web:485ffb8374d235e35089b5',
    messagingSenderId: '335135674224',
    projectId: 'flutter-auth-app-abf30',
    authDomain: 'flutter-auth-app-abf30.firebaseapp.com',
    storageBucket: 'flutter-auth-app-abf30.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTmpiVWF3HFDwM7DHdvNgvGbgRakaG1XQ',
    appId: '1:335135674224:android:4cf404bba5cd768a5089b5',
    messagingSenderId: '335135674224',
    projectId: 'flutter-auth-app-abf30',
    storageBucket: 'flutter-auth-app-abf30.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpf8wDC2x6MzsHI1ST6rSGID9f63u_mgc',
    appId: '1:335135674224:ios:be0c74b273a49b615089b5',
    messagingSenderId: '335135674224',
    projectId: 'flutter-auth-app-abf30',
    storageBucket: 'flutter-auth-app-abf30.firebasestorage.app',
    iosBundleId: 'com.example.flutterAuthApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpf8wDC2x6MzsHI1ST6rSGID9f63u_mgc',
    appId: '1:335135674224:ios:be0c74b273a49b615089b5',
    messagingSenderId: '335135674224',
    projectId: 'flutter-auth-app-abf30',
    storageBucket: 'flutter-auth-app-abf30.firebasestorage.app',
    iosBundleId: 'com.example.flutterAuthApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAG9zvukee4PtoW7k2YWIn6MufpU695BDA',
    appId: '1:335135674224:web:5bede1d5587f79dd5089b5',
    messagingSenderId: '335135674224',
    projectId: 'flutter-auth-app-abf30',
    authDomain: 'flutter-auth-app-abf30.firebaseapp.com',
    storageBucket: 'flutter-auth-app-abf30.firebasestorage.app',
  );
}
